/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.DungNgoc.UI;

/**
 *
 * @author lenonvo
 */
public class BaoCao extends javax.swing.JInternalFrame {

    /**
     * Creates new form BaoCao
     */
    public BaoCao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblBaoCaoCuoiNgay = new javax.swing.JLabel();
        lblMoiQuanTam = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        PanelHangHoa = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHangHoa = new javax.swing.JTable();
        PanelBanHang = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBanHang = new javax.swing.JTable();
        PanelTongHop = new javax.swing.JPanel();
        lblLoc = new javax.swing.JLabel();
        lblSoMatHangDaBan = new javax.swing.JLabel();
        lblSoGiaoDich = new javax.swing.JLabel();
        txtSLSPDaBan = new javax.swing.JTextField();
        lblSoLuongSPDaBan = new javax.swing.JLabel();
        txtSLDaBan = new javax.swing.JTextField();
        lblSPBanNN = new javax.swing.JLabel();
        lblSPBanIN = new javax.swing.JLabel();
        txtSPBanIN = new javax.swing.JTextField();
        lblDoanhThu = new javax.swing.JLabel();
        txtSoGiaoDich = new javax.swing.JTextField();
        txtSPBanNN = new javax.swing.JTextField();
        txtDoanhThu = new javax.swing.JTextField();
        radioDoanhThu = new javax.swing.JRadioButton();
        radioSoLuong = new javax.swing.JRadioButton();
        cbbMoiQuanTam = new javax.swing.JComboBox<>();
        lblThoiGian = new javax.swing.JLabel();
        btnShow = new javax.swing.JButton();
        txtThoiGian = new com.toedter.calendar.JDateChooser();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        lblBaoCaoCuoiNgay1 = new javax.swing.JLabel();
        lblMoiQuanTam1 = new javax.swing.JLabel();
        tabs1 = new javax.swing.JTabbedPane();
        PanelHangHoa1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHangHoa1 = new javax.swing.JTable();
        PanelBanHang1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblBanHang1 = new javax.swing.JTable();
        PanelTongHop1 = new javax.swing.JPanel();
        lblLoc1 = new javax.swing.JLabel();
        lblSoMatHangDaBan1 = new javax.swing.JLabel();
        lblSoGiaoDich1 = new javax.swing.JLabel();
        txtSLSPDaBan1 = new javax.swing.JTextField();
        lblSoLuongSPDaBan1 = new javax.swing.JLabel();
        txtSLDaBan1 = new javax.swing.JTextField();
        lblSPBanNN1 = new javax.swing.JLabel();
        lblSPBanIN1 = new javax.swing.JLabel();
        txtSPBanIN1 = new javax.swing.JTextField();
        lblDoanhThu1 = new javax.swing.JLabel();
        txtSoGiaoDich1 = new javax.swing.JTextField();
        txtSPBanNN1 = new javax.swing.JTextField();
        txtDoanhThu1 = new javax.swing.JTextField();
        radioDoanhThu1 = new javax.swing.JRadioButton();
        radioSoLuong1 = new javax.swing.JRadioButton();
        cbbMoiQuanTam1 = new javax.swing.JComboBox<>();
        lblThoiGian1 = new javax.swing.JLabel();
        btnShow1 = new javax.swing.JButton();
        txtThoiGian1 = new com.toedter.calendar.JDateChooser();

        lblBaoCaoCuoiNgay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblBaoCaoCuoiNgay.setText("Báo cáo cuối ngày");

        lblMoiQuanTam.setText("Mối quan tâm");

        tabs.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 51, 255))); // NOI18N

        tblHangHoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ SP", "TÊN SP", "SỐ LƯỢNG SẢN PHẨM ", "DOANH THU"
            }
        ));
        tblHangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHangHoaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHangHoa);

        javax.swing.GroupLayout PanelHangHoaLayout = new javax.swing.GroupLayout(PanelHangHoa);
        PanelHangHoa.setLayout(PanelHangHoaLayout);
        PanelHangHoaLayout.setHorizontalGroup(
            PanelHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHangHoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelHangHoaLayout.setVerticalGroup(
            PanelHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHangHoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("Hàng hóa", PanelHangHoa);

        tblBanHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ GD", "THỜI GIAN", "SỐ LƯỢNG BÁN ", "DOANH THU"
            }
        ));
        tblBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBanHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBanHang);

        javax.swing.GroupLayout PanelBanHangLayout = new javax.swing.GroupLayout(PanelBanHang);
        PanelBanHang.setLayout(PanelBanHangLayout);
        PanelBanHangLayout.setHorizontalGroup(
            PanelBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBanHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelBanHangLayout.setVerticalGroup(
            PanelBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBanHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("Bán hàng", PanelBanHang);

        lblLoc.setText("Lọc");

        lblSoMatHangDaBan.setText("Số mặt hàng đã bán");

        lblSoGiaoDich.setText("Số giao dịch");

        txtSLSPDaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSLSPDaBanActionPerformed(evt);
            }
        });

        lblSoLuongSPDaBan.setText("Số lượng sản phẩm đã bán");

        lblSPBanNN.setText("Sản phẩm bán NN");

        lblSPBanIN.setText("Sản phẩm bán IN");

        lblDoanhThu.setText("Doanh thu");

        buttonGroup1.add(radioDoanhThu);
        radioDoanhThu.setText("Doanh thu");

        buttonGroup1.add(radioSoLuong);
        radioSoLuong.setText("Số lượng");

        javax.swing.GroupLayout PanelTongHopLayout = new javax.swing.GroupLayout(PanelTongHop);
        PanelTongHop.setLayout(PanelTongHopLayout);
        PanelTongHopLayout.setHorizontalGroup(
            PanelTongHopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTongHopLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PanelTongHopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTongHopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTongHopLayout.createSequentialGroup()
                            .addComponent(lblSoGiaoDich)
                            .addGap(112, 112, 112))
                        .addGroup(PanelTongHopLayout.createSequentialGroup()
                            .addGroup(PanelTongHopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSPBanNN)
                                .addComponent(lblDoanhThu)
                                .addComponent(lblSPBanIN)
                                .addComponent(lblSoMatHangDaBan)
                                .addComponent(lblSoLuongSPDaBan))
                            .addGap(39, 39, 39)))
                    .addGroup(PanelTongHopLayout.createSequentialGroup()
                        .addComponent(lblLoc)
                        .addGap(153, 153, 153)))
                .addGroup(PanelTongHopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTongHopLayout.createSequentialGroup()
                        .addComponent(radioDoanhThu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioSoLuong))
                    .addGroup(PanelTongHopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtSLDaBan, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                        .addComponent(txtSPBanNN, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                        .addComponent(txtSLSPDaBan)
                        .addComponent(txtSoGiaoDich)
                        .addComponent(txtSPBanIN)
                        .addComponent(txtDoanhThu)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        PanelTongHopLayout.setVerticalGroup(
            PanelTongHopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTongHopLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PanelTongHopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLoc)
                    .addGroup(PanelTongHopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioDoanhThu)
                        .addComponent(radioSoLuong)))
                .addGap(16, 16, 16)
                .addGroup(PanelTongHopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoGiaoDich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoGiaoDich))
                .addGap(20, 20, 20)
                .addGroup(PanelTongHopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSLDaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoMatHangDaBan))
                .addGap(18, 18, 18)
                .addGroup(PanelTongHopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSLSPDaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoLuongSPDaBan))
                .addGap(18, 18, 18)
                .addGroup(PanelTongHopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSPBanNN)
                    .addComponent(txtSPBanNN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelTongHopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSPBanIN)
                    .addComponent(txtSPBanIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelTongHopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDoanhThu))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        tabs.addTab("Tổng hợp", PanelTongHop);

        cbbMoiQuanTam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblThoiGian.setText("Thời gian");

        btnShow.setText("Show");

        lblBaoCaoCuoiNgay1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblBaoCaoCuoiNgay1.setText("Báo cáo cuối ngày");

        lblMoiQuanTam1.setText("Mối quan tâm");

        tabs1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 51, 255))); // NOI18N

        tblHangHoa1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ SP", "TÊN SP", "SỐ LƯỢNG SẢN PHẨM ", "DOANH THU"
            }
        ));
        tblHangHoa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHangHoa1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblHangHoa1);

        javax.swing.GroupLayout PanelHangHoa1Layout = new javax.swing.GroupLayout(PanelHangHoa1);
        PanelHangHoa1.setLayout(PanelHangHoa1Layout);
        PanelHangHoa1Layout.setHorizontalGroup(
            PanelHangHoa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHangHoa1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelHangHoa1Layout.setVerticalGroup(
            PanelHangHoa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHangHoa1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs1.addTab("Hàng hóa", PanelHangHoa1);

        tblBanHang1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ GD", "THỜI GIAN", "SỐ LƯỢNG BÁN ", "DOANH THU"
            }
        ));
        tblBanHang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBanHang1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblBanHang1);

        javax.swing.GroupLayout PanelBanHang1Layout = new javax.swing.GroupLayout(PanelBanHang1);
        PanelBanHang1.setLayout(PanelBanHang1Layout);
        PanelBanHang1Layout.setHorizontalGroup(
            PanelBanHang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBanHang1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelBanHang1Layout.setVerticalGroup(
            PanelBanHang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBanHang1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs1.addTab("Bán hàng", PanelBanHang1);

        lblLoc1.setText("Lọc");

        lblSoMatHangDaBan1.setText("Số mặt hàng đã bán");

        lblSoGiaoDich1.setText("Số giao dịch");

        txtSLSPDaBan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSLSPDaBan1ActionPerformed(evt);
            }
        });

        lblSoLuongSPDaBan1.setText("Số lượng sản phẩm đã bán");

        lblSPBanNN1.setText("Sản phẩm bán NN");

        lblSPBanIN1.setText("Sản phẩm bán IN");

        lblDoanhThu1.setText("Doanh thu");

        buttonGroup1.add(radioDoanhThu1);
        radioDoanhThu1.setText("Doanh thu");

        buttonGroup1.add(radioSoLuong1);
        radioSoLuong1.setText("Số lượng");

        javax.swing.GroupLayout PanelTongHop1Layout = new javax.swing.GroupLayout(PanelTongHop1);
        PanelTongHop1.setLayout(PanelTongHop1Layout);
        PanelTongHop1Layout.setHorizontalGroup(
            PanelTongHop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTongHop1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PanelTongHop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTongHop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTongHop1Layout.createSequentialGroup()
                            .addComponent(lblSoGiaoDich1)
                            .addGap(112, 112, 112))
                        .addGroup(PanelTongHop1Layout.createSequentialGroup()
                            .addGroup(PanelTongHop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSPBanNN1)
                                .addComponent(lblDoanhThu1)
                                .addComponent(lblSPBanIN1)
                                .addComponent(lblSoMatHangDaBan1)
                                .addComponent(lblSoLuongSPDaBan1))
                            .addGap(39, 39, 39)))
                    .addGroup(PanelTongHop1Layout.createSequentialGroup()
                        .addComponent(lblLoc1)
                        .addGap(153, 153, 153)))
                .addGroup(PanelTongHop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTongHop1Layout.createSequentialGroup()
                        .addComponent(radioDoanhThu1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioSoLuong1))
                    .addGroup(PanelTongHop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtSLDaBan1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                        .addComponent(txtSPBanNN1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                        .addComponent(txtSLSPDaBan1)
                        .addComponent(txtSoGiaoDich1)
                        .addComponent(txtSPBanIN1)
                        .addComponent(txtDoanhThu1)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        PanelTongHop1Layout.setVerticalGroup(
            PanelTongHop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTongHop1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PanelTongHop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLoc1)
                    .addGroup(PanelTongHop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioDoanhThu1)
                        .addComponent(radioSoLuong1)))
                .addGap(16, 16, 16)
                .addGroup(PanelTongHop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoGiaoDich1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoGiaoDich1))
                .addGap(20, 20, 20)
                .addGroup(PanelTongHop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSLDaBan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoMatHangDaBan1))
                .addGap(18, 18, 18)
                .addGroup(PanelTongHop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSLSPDaBan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoLuongSPDaBan1))
                .addGap(18, 18, 18)
                .addGroup(PanelTongHop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSPBanNN1)
                    .addComponent(txtSPBanNN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelTongHop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSPBanIN1)
                    .addComponent(txtSPBanIN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelTongHop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDoanhThu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDoanhThu1))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        tabs1.addTab("Tổng hợp", PanelTongHop1);

        cbbMoiQuanTam1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblThoiGian1.setText("Thời gian");

        btnShow1.setText("Show");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMoiQuanTam1)
                        .addGap(18, 18, 18)
                        .addComponent(cbbMoiQuanTam1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(lblThoiGian1)
                        .addGap(18, 18, 18)
                        .addComponent(txtThoiGian1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnShow1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(lblBaoCaoCuoiNgay1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tabs1, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBaoCaoCuoiNgay1)
                .addGap(17, 17, 17)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMoiQuanTam1)
                        .addComponent(cbbMoiQuanTam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblThoiGian1)
                        .addComponent(btnShow1))
                    .addComponent(txtThoiGian1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addGap(89, 89, 89)
                    .addComponent(tabs1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMoiQuanTam)
                        .addGap(18, 18, 18)
                        .addComponent(cbbMoiQuanTam, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(lblThoiGian)
                        .addGap(18, 18, 18)
                        .addComponent(txtThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnShow, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(lblBaoCaoCuoiNgay)))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tabs, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBaoCaoCuoiNgay)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMoiQuanTam)
                        .addComponent(cbbMoiQuanTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblThoiGian)
                        .addComponent(btnShow))
                    .addComponent(txtThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(401, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(89, 89, 89)
                    .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblHangHoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHangHoaMouseClicked
        if (evt.getClickCount() == 2) {
            this.row = tblHangHoa.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblHangHoaMouseClicked

    private void txtSLSPDaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSLSPDaBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSLSPDaBanActionPerformed

    private void tblBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBanHangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblBanHangMouseClicked

    private void tblHangHoa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHangHoa1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblHangHoa1MouseClicked

    private void tblBanHang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBanHang1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblBanHang1MouseClicked

    private void txtSLSPDaBan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSLSPDaBan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSLSPDaBan1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBanHang;
    private javax.swing.JPanel PanelBanHang1;
    private javax.swing.JPanel PanelHangHoa;
    private javax.swing.JPanel PanelHangHoa1;
    private javax.swing.JPanel PanelTongHop;
    private javax.swing.JPanel PanelTongHop1;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnShow1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbMoiQuanTam;
    private javax.swing.JComboBox<String> cbbMoiQuanTam1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblBaoCaoCuoiNgay;
    private javax.swing.JLabel lblBaoCaoCuoiNgay1;
    private javax.swing.JLabel lblDoanhThu;
    private javax.swing.JLabel lblDoanhThu1;
    private javax.swing.JLabel lblLoc;
    private javax.swing.JLabel lblLoc1;
    private javax.swing.JLabel lblMoiQuanTam;
    private javax.swing.JLabel lblMoiQuanTam1;
    private javax.swing.JLabel lblSPBanIN;
    private javax.swing.JLabel lblSPBanIN1;
    private javax.swing.JLabel lblSPBanNN;
    private javax.swing.JLabel lblSPBanNN1;
    private javax.swing.JLabel lblSoGiaoDich;
    private javax.swing.JLabel lblSoGiaoDich1;
    private javax.swing.JLabel lblSoLuongSPDaBan;
    private javax.swing.JLabel lblSoLuongSPDaBan1;
    private javax.swing.JLabel lblSoMatHangDaBan;
    private javax.swing.JLabel lblSoMatHangDaBan1;
    private javax.swing.JLabel lblThoiGian;
    private javax.swing.JLabel lblThoiGian1;
    private javax.swing.JRadioButton radioDoanhThu;
    private javax.swing.JRadioButton radioDoanhThu1;
    private javax.swing.JRadioButton radioSoLuong;
    private javax.swing.JRadioButton radioSoLuong1;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTabbedPane tabs1;
    private javax.swing.JTable tblBanHang;
    private javax.swing.JTable tblBanHang1;
    private javax.swing.JTable tblHangHoa;
    private javax.swing.JTable tblHangHoa1;
    private javax.swing.JTextField txtDoanhThu;
    private javax.swing.JTextField txtDoanhThu1;
    private javax.swing.JTextField txtSLDaBan;
    private javax.swing.JTextField txtSLDaBan1;
    private javax.swing.JTextField txtSLSPDaBan;
    private javax.swing.JTextField txtSLSPDaBan1;
    private javax.swing.JTextField txtSPBanIN;
    private javax.swing.JTextField txtSPBanIN1;
    private javax.swing.JTextField txtSPBanNN;
    private javax.swing.JTextField txtSPBanNN1;
    private javax.swing.JTextField txtSoGiaoDich;
    private javax.swing.JTextField txtSoGiaoDich1;
    private com.toedter.calendar.JDateChooser txtThoiGian;
    private com.toedter.calendar.JDateChooser txtThoiGian1;
    // End of variables declaration//GEN-END:variables
}
