/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.DungNgoc.UI;

import com.DungNgoc.DAO.DongMayDAO;
import com.DungNgoc.DAO.HangMayDAO;
import com.DungNgoc.DAO.LoaiMayDAO;
import com.DungNgoc.DAO.MauDAO;
import com.DungNgoc.DAO.PhienBanDAO;
import com.DungNgoc.DAO.SanPhamDAO;
import com.DungNgoc.DAO.SanPhamTableDao;
import com.DungNgoc.entitys.DongMay;
import com.DungNgoc.entitys.HangMay;
import com.DungNgoc.entitys.LoaiMay;
import com.DungNgoc.entitys.Mau;
import com.DungNgoc.entitys.PhienBan;
import com.DungNgoc.entitys.SanPham;
import com.DungNgoc.entitys.SanPhamTable;
import com.DungNgoc.untils.Auth;
import com.DungNgoc.untils.Exceptions;
import com.DungNgoc.untils.MsgBox;
import com.DungNgoc.untils.Xdate;
import com.DungNgoc.untils.Ximage;
import com.DungNgoc.untils.Xmoney;
import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LINH
 */
public class JQuanLySanPham extends javax.swing.JInternalFrame {

    DefaultTableModel model, modelRac;
    HangMayDAO hmdao = new HangMayDAO();
    DongMayDAO dmdao = new DongMayDAO();
    LoaiMayDAO lmdao = new LoaiMayDAO();
    MauDAO maudao = new MauDAO();
    PhienBanDAO pbdao = new PhienBanDAO();
    SanPhamDAO spdao = new SanPhamDAO();
    SanPhamTableDao sptdao = new SanPhamTableDao();
    int index = -1, row = -1, page = 0, pageRac = 0;
    List<SanPhamTable> list;
    List<SanPham> lstSP;
    List<HangMay> listHM;
    List<DongMay> listDM;
    List<LoaiMay> listLM;
    List<PhienBan> listPB;
    List<Mau> listMau;

    /**
     * Creates new form JQuanLySanPham
     */
    public JQuanLySanPham() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupTrangThai = new javax.swing.ButtonGroup();
        frame = new javax.swing.JFrame();
        popup = new javax.swing.JPopupMenu();
        Refesh = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        tabs = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        lblHangMay = new javax.swing.JLabel();
        cbbHangMay1 = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        lblDongMay = new javax.swing.JLabel();
        cbbDongMay1 = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        lblLoaiMay = new javax.swing.JLabel();
        cbbLoaiMay1 = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        lblPB = new javax.swing.JLabel();
        cbbPhienBan1 = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        lblRAMMay = new javax.swing.JLabel();
        cbbRAM1 = new javax.swing.JComboBox<>();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        lblDungLuongMay = new javax.swing.JLabel();
        cbbDungLuong1 = new javax.swing.JComboBox<>();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtTim = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lblMaSP = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        lblTenSP = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        lblHang = new javax.swing.JLabel();
        cbbHangMay = new javax.swing.JComboBox<>();
        lblAnh = new javax.swing.JLabel();
        lblDong = new javax.swing.JLabel();
        lblLoai = new javax.swing.JLabel();
        cbbLoaiMay = new javax.swing.JComboBox<>();
        cbbDongMay = new javax.swing.JComboBox<>();
        lblTinhTrang = new javax.swing.JLabel();
        radioMayMoi = new javax.swing.JRadioButton();
        radioMayCu = new javax.swing.JRadioButton();
        lblGia = new javax.swing.JLabel();
        txtGiaSP = new javax.swing.JTextField();
        lblSoLuong = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnDau = new javax.swing.JButton();
        btnLui = new javax.swing.JButton();
        btnTien = new javax.swing.JButton();
        btnCuoi = new javax.swing.JButton();
        lblRAM = new javax.swing.JLabel();
        cbbRAM = new javax.swing.JComboBox<>();
        lblPhienBan = new javax.swing.JLabel();
        cbbPhienBan = new javax.swing.JComboBox<>();
        btnThemThongSo = new javax.swing.JButton();
        lblDungLuong = new javax.swing.JLabel();
        cbbDungLuong = new javax.swing.JComboBox<>();
        lblMauMay = new javax.swing.JLabel();
        cbbMauMay = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThungRac = new javax.swing.JTable();
        jPanel20 = new javax.swing.JPanel();
        btnPrevious3 = new javax.swing.JButton();
        btnNext3 = new javax.swing.JButton();
        btnKhoiPhuc = new javax.swing.JButton();
        lblQLSP = new javax.swing.JLabel();

        javax.swing.GroupLayout frameLayout = new javax.swing.GroupLayout(frame.getContentPane());
        frame.getContentPane().setLayout(frameLayout);
        frameLayout.setHorizontalGroup(
            frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        frameLayout.setVerticalGroup(
            frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        Refesh.setText("Refesh");
        Refesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefeshActionPerformed(evt);
            }
        });
        popup.add(Refesh);

        setClosable(true);

        jPanel1.setComponentPopupMenu(popup);

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên máy", "RAM", "Dung lượng", "Màu sắc", "Tình trạng", "Giá", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPham);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblHangMay.setText("Hãng máy");

        cbbHangMay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbHangMay1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblHangMay)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cbbHangMay1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHangMay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbHangMay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDongMay.setText("Dòng máy");

        cbbDongMay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbDongMay1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbDongMay1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lblDongMay)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblDongMay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbDongMay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblLoaiMay.setText("Loại máy");

        cbbLoaiMay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbLoaiMay1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbLoaiMay1, 0, 147, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(lblLoaiMay)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lblLoaiMay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbLoaiMay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPB.setText("Phiên bản");

        cbbPhienBan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbPhienBan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(lblPB)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cbbPhienBan1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbPhienBan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnPrevious.setText("<<");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrevious)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNext)
                .addGap(27, 27, 27))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevious)
                    .addComponent(btnNext))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblRAMMay.setText("RAM");

        cbbRAM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbRAM1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbRAM1, 0, 147, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(lblRAMMay)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRAMMay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbbRAM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDungLuongMay.setText("Dung lượng");

        cbbDungLuong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbDungLuong1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbDungLuong1, 0, 147, Short.MAX_VALUE)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(lblDungLuongMay)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDungLuongMay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbDungLuong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel20.setText("Tìm kiếm");

        txtTim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        tabs.addTab("Danh sách", jPanel2);

        lblMaSP.setText("Mã sản phẩm");

        lblTenSP.setText("Tên sản phẩm");

        lblHang.setText("Hãng");

        cbbHangMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbHangMayActionPerformed(evt);
            }
        });

        lblAnh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhMouseClicked(evt);
            }
        });

        lblDong.setText("Dòng máy");

        lblLoai.setText("Loại máy");

        cbbLoaiMay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbbLoaiMayMouseEntered(evt);
            }
        });

        cbbDongMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbDongMayActionPerformed(evt);
            }
        });

        lblTinhTrang.setText("Tình trạng");

        groupTrangThai.add(radioMayMoi);
        radioMayMoi.setText("Máy mới");

        groupTrangThai.add(radioMayCu);
        radioMayCu.setText("Máy cũ");

        lblGia.setText("Giá sản phẩm");

        lblSoLuong.setText("Số lượng");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMoi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnMoi))
                .addContainerGap())
        );

        btnDau.setText("|<");
        btnDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDauActionPerformed(evt);
            }
        });

        btnLui.setText("<<");
        btnLui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuiActionPerformed(evt);
            }
        });

        btnTien.setText(">>");
        btnTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTienActionPerformed(evt);
            }
        });

        btnCuoi.setText(">|");
        btnCuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLui)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCuoi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDau)
                    .addComponent(btnLui)
                    .addComponent(btnTien)
                    .addComponent(btnCuoi))
                .addContainerGap())
        );

        lblRAM.setText("RAM");

        cbbRAM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4GB", "6Gb", "8GB", "12GB", "16GB" }));

        lblPhienBan.setText("Phiên bản");

        cbbPhienBan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnThemThongSo.setText("Thêm thông số mới");
        btnThemThongSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemThongSoActionPerformed(evt);
            }
        });

        lblDungLuong.setText("Dung lượng");

        cbbDungLuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "32GB", "64GB", "128GB", "256GB", "512GB", "1TB", "2TB" }));

        lblMauMay.setText("Màu");

        cbbMauMay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblHang)
                                        .addGap(138, 138, 138)
                                        .addComponent(lblDong))
                                    .addComponent(txtGiaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTenSP)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtMaSP, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTenSP, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblRAM)
                                                .addComponent(cbbRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cbbHangMay, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblTinhTrang))
                                            .addGap(33, 33, 33)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                            .addComponent(lblDungLuong)
                                                            .addGap(65, 65, 65)
                                                            .addComponent(lblMauMay))
                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(cbbDungLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(radioMayMoi))
                                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                    .addGap(55, 55, 55)
                                                                    .addComponent(radioMayCu))
                                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                    .addGap(18, 18, 18)
                                                                    .addComponent(cbbMauMay, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblPhienBan)
                                                        .addComponent(cbbPhienBan, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                    .addComponent(cbbDongMay, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(65, 65, 65)
                                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblLoai)
                                                        .addComponent(cbbLoaiMay, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(btnThemThongSo)))))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblMaSP)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblGia)
                                .addComponent(lblSoLuong)
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMaSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTenSP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHang)
                            .addComponent(lblDong)
                            .addComponent(lblLoai))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbHangMay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbLoaiMay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbDongMay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRAM)
                            .addComponent(lblPhienBan)
                            .addComponent(lblDungLuong)
                            .addComponent(lblMauMay))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbRAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbPhienBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbDungLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbMauMay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTinhTrang)
                    .addComponent(radioMayMoi)
                    .addComponent(radioMayCu))
                .addGap(18, 18, 18)
                .addComponent(lblGia)
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGiaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemThongSo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSoLuong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabs.addTab("Thông tin", jPanel4);

        tblThungRac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên máy", "Loại", "Dung lượng", "Màu sắc", "Tình trạng", "Giá", "Số lượng"
            }
        ));
        tblThungRac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThungRacMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblThungRac);

        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnPrevious3.setText("<<");
        btnPrevious3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevious3ActionPerformed(evt);
            }
        });

        btnNext3.setText(">>");
        btnNext3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext3ActionPerformed(evt);
            }
        });

        btnKhoiPhuc.setText("Khôi phục");
        btnKhoiPhuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoiPhucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrevious3)
                .addGap(258, 258, 258)
                .addComponent(btnKhoiPhuc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNext3)
                .addGap(27, 27, 27))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevious3)
                    .addComponent(btnNext3)
                    .addComponent(btnKhoiPhuc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        tabs.addTab("Thùng rác", jPanel3);

        lblQLSP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblQLSP.setText("QUẢN LÝ SẢN PHẨM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(lblQLSP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblQLSP)
                .addGap(7, 7, 7)
                .addComponent(tabs))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemThongSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemThongSoActionPerformed
        new JThongSoMoi(frame, true).setVisible(true);
    }//GEN-LAST:event_btnThemThongSoActionPerformed

    private void cbbHangMay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbHangMay1ActionPerformed
        row = cbbHangMay1.getSelectedIndex();
        if (row >= 0) {
            fillDongMay1(row);
            fillTable();
        }
    }//GEN-LAST:event_cbbHangMay1ActionPerformed

    private void cbbDongMay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbDongMay1ActionPerformed
        row = cbbDongMay1.getSelectedIndex();
        if (row >= 0) {
            fillLoaiMay1(row);
            fillTable();
        }
    }//GEN-LAST:event_cbbDongMay1ActionPerformed

    private void cbbLoaiMay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbLoaiMay1ActionPerformed
        row = cbbLoaiMay1.getSelectedIndex();
        if (row >= 0) {
            fillTable();
        }
    }//GEN-LAST:event_cbbLoaiMay1ActionPerformed

    private void cbbPhienBan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbPhienBan1ActionPerformed
        row = cbbLoaiMay1.getSelectedIndex();
        if (row >= 0) {
            fillTable();
        }
    }//GEN-LAST:event_cbbPhienBan1ActionPerformed

    private void cbbRAM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbRAM1ActionPerformed
        row = cbbLoaiMay1.getSelectedIndex();
        if (row >= 0) {
            fillTable();
        }
    }//GEN-LAST:event_cbbRAM1ActionPerformed

    private void cbbDungLuong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbDungLuong1ActionPerformed
        row = cbbLoaiMay1.getSelectedIndex();
        if (row >= 0) {
            fillTable();
        }
    }//GEN-LAST:event_cbbDungLuong1ActionPerformed

    private void txtTimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKeyReleased
        fillTable();
    }//GEN-LAST:event_txtTimKeyReleased

    private void lblAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhMouseClicked
        chonAnh();
    }//GEN-LAST:event_lblAnhMouseClicked

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        if (evt.getClickCount() == 2) {
            this.index = tblSanPham.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDauActionPerformed
        first();
    }//GEN-LAST:event_btnDauActionPerformed

    private void btnLuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuiActionPerformed
        prev();
    }//GEN-LAST:event_btnLuiActionPerformed

    private void btnTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTienActionPerformed
        next();
    }//GEN-LAST:event_btnTienActionPerformed

    private void btnCuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuoiActionPerformed
        last();
    }//GEN-LAST:event_btnCuoiActionPerformed

    private void cbbHangMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbHangMayActionPerformed
        row = cbbHangMay.getSelectedIndex();
        if (row >= 0) {
            fillDongMay(row);
        }
    }//GEN-LAST:event_cbbHangMayActionPerformed

    private void cbbDongMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbDongMayActionPerformed
        row = cbbDongMay.getSelectedIndex();
        if (row >= 0) {
            fillLoaiMay(row);
        }
    }//GEN-LAST:event_cbbDongMayActionPerformed

    private void btnKhoiPhucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoiPhucActionPerformed
        restore();
    }//GEN-LAST:event_btnKhoiPhucActionPerformed

    private void tblThungRacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThungRacMouseClicked

    }//GEN-LAST:event_tblThungRacMouseClicked

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        prevPage();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        nextPage();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevious3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevious3ActionPerformed
        prevPageRac();
    }//GEN-LAST:event_btnPrevious3ActionPerformed

    private void btnNext3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext3ActionPerformed
        nextPageRac();
    }//GEN-LAST:event_btnNext3ActionPerformed

    private void cbbLoaiMayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbLoaiMayMouseEntered
        txtTenSP.setText(cbbLoaiMay.getSelectedItem().toString());
    }//GEN-LAST:event_cbbLoaiMayMouseEntered

    private void RefeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefeshActionPerformed
        // TODO add your handling code here:
        fillHangMay();
        fillDongMay(0);
        fillLoaiMay(0);
        fillPhienBan();
        fillMau();
    }//GEN-LAST:event_RefeshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Refesh;
    private javax.swing.JButton btnCuoi;
    private javax.swing.JButton btnDau;
    private javax.swing.JButton btnKhoiPhuc;
    private javax.swing.JButton btnLui;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNext3;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnPrevious3;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemThongSo;
    private javax.swing.JButton btnTien;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbDongMay;
    private javax.swing.JComboBox<String> cbbDongMay1;
    private javax.swing.JComboBox<String> cbbDungLuong;
    private javax.swing.JComboBox<String> cbbDungLuong1;
    private javax.swing.JComboBox<String> cbbHangMay;
    private javax.swing.JComboBox<String> cbbHangMay1;
    private javax.swing.JComboBox<String> cbbLoaiMay;
    private javax.swing.JComboBox<String> cbbLoaiMay1;
    private javax.swing.JComboBox<String> cbbMauMay;
    private javax.swing.JComboBox<String> cbbPhienBan;
    private javax.swing.JComboBox<String> cbbPhienBan1;
    private javax.swing.JComboBox<String> cbbRAM;
    private javax.swing.JComboBox<String> cbbRAM1;
    private javax.swing.JFrame frame;
    private javax.swing.ButtonGroup groupTrangThai;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JLabel lblDong;
    private javax.swing.JLabel lblDongMay;
    private javax.swing.JLabel lblDungLuong;
    private javax.swing.JLabel lblDungLuongMay;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblHang;
    private javax.swing.JLabel lblHangMay;
    private javax.swing.JLabel lblLoai;
    private javax.swing.JLabel lblLoaiMay;
    private javax.swing.JLabel lblMaSP;
    private javax.swing.JLabel lblMauMay;
    private javax.swing.JLabel lblPB;
    private javax.swing.JLabel lblPhienBan;
    private javax.swing.JLabel lblQLSP;
    private javax.swing.JLabel lblRAM;
    private javax.swing.JLabel lblRAMMay;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JLabel lblTinhTrang;
    private javax.swing.JPopupMenu popup;
    private javax.swing.JRadioButton radioMayCu;
    private javax.swing.JRadioButton radioMayMoi;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTable tblThungRac;
    private javax.swing.JTextField txtGiaSP;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables

    private void init() {
        tblSanPham.setAutoCreateRowSorter(true);
        fillRam();
        fillDungLuong();
        fillHangMay1();
        fillDongMay1(0);
        fillLoaiMay1(0);
        fillPhienBan1();
        fillHangMay();
        fillDongMay(0);
        fillLoaiMay(0);
        fillPhienBan();
        fillTable();
        fillTableThungRac();
        fillMau();
//        txtTenSP.setText(cbbLoaiMay.getSelectedItem().toString());
        updateStatus();
    }

    void fillRam() {
        cbbRAM.addItem("4GB");
        cbbRAM.addItem("6GB");
        cbbRAM.addItem("8GB");
        cbbRAM.addItem("12GB");
        cbbRAM.addItem("14GB");

        cbbRAM1.addItem("");
        cbbRAM1.addItem("4GB");
        cbbRAM1.addItem("6GB");
        cbbRAM1.addItem("8GB");
        cbbRAM1.addItem("12GB");
        cbbRAM1.addItem("14GB");
    }

    void fillDungLuong() {
        cbbDungLuong.addItem("32GB");
        cbbDungLuong.addItem("64GB");
        cbbDungLuong.addItem("128GB");
        cbbDungLuong.addItem("256GB");
        cbbDungLuong.addItem("512GB");
        cbbDungLuong.addItem("1TB");
        cbbDungLuong.addItem("2TB");

        cbbDungLuong1.addItem("");
        cbbDungLuong1.addItem("32GB");
        cbbDungLuong1.addItem("64GB");
        cbbDungLuong1.addItem("128GB");
        cbbDungLuong1.addItem("256GB");
        cbbDungLuong1.addItem("512GB");
        cbbDungLuong1.addItem("1TB");
        cbbDungLuong1.addItem("2TB");
    }

    void fillHangMay1() {
        try {
            listHM.clear();
        } catch (Exception e) {
        }
        cbbHangMay1.removeAllItems();
        listHM = hmdao.selectAll();
        cbbHangMay1.addItem("");
        for (HangMay x : listHM) {
            cbbHangMay1.addItem(x.getName());
        }
    }

    void fillDongMay1(int index) {
        try {
            listDM.clear();
        } catch (Exception e) {
        }
        cbbDongMay1.removeAllItems();
        cbbDongMay1.addItem("");
        if (index > 0) {
            listDM = dmdao.selectByHangMay(listHM.get(index - 1).getTypeID());
            for (DongMay x : listDM) {
                cbbDongMay1.addItem(x.getName());
            }
        }
    }

    void fillLoaiMay1(int index) {
        try {
            listLM.clear();
        } catch (Exception e) {
        }
        cbbLoaiMay1.removeAllItems();
        cbbLoaiMay1.addItem("");
        if (index > 0) {
            listLM = lmdao.selectByDongMay(listDM.get(index - 1).getTag());
            for (LoaiMay x : listLM) {
                cbbLoaiMay1.addItem(x.getName());
            }
        }
    }

    void fillPhienBan1() {
        try {
            listPB.clear();
        } catch (Exception e) {
        }
        cbbLoaiMay1.removeAllItems();
        cbbLoaiMay1.addItem("");
        listPB = pbdao.selectAll();
        for (PhienBan x : listPB) {
            cbbPhienBan1.addItem(x.getName());
        }
    }

    void fillHangMay() {
        try {
            listHM.clear();
        } catch (Exception e) {
        }
        cbbHangMay.removeAllItems();
        listHM = hmdao.selectAll();
        for (HangMay x : listHM) {
            cbbHangMay.addItem(x.getName());
        }
    }

    void fillDongMay(int index) {
        try {
            listDM.clear();
        } catch (Exception e) {
        }
        cbbDongMay.removeAllItems();
        listDM = dmdao.selectByHangMay(listHM.get(index).getTypeID());
        for (DongMay x : listDM) {
            cbbDongMay.addItem(x.getName());
        }
    }

    void fillLoaiMay(int index) {
        try {
            listLM.clear();
        } catch (Exception e) {
        }
        cbbLoaiMay.removeAllItems();
        listLM = lmdao.selectByDongMay(listDM.get(index).getTag());
        for (LoaiMay x : listLM) {
            cbbLoaiMay.addItem(x.getName());
        }
    }

    void fillPhienBan() {
        cbbPhienBan.removeAllItems();
        try {
            listPB.clear();
        } catch (Exception e) {
        }
        listPB = pbdao.selectAll();
        for (PhienBan x : listPB) {
            cbbPhienBan.addItem(x.getName());
        }
    }

    void fillTable() {
        model = (DefaultTableModel) tblSanPham.getModel();
        model.setRowCount(0);
        String hang = cbbHangMay1.getSelectedItem() == null ? "" : cbbHangMay1.getSelectedItem() + "";
        String dong = cbbDongMay1.getSelectedItem() == null ? "" : cbbDongMay1.getSelectedItem() + "";
        String loai = cbbLoaiMay1.getSelectedItem() == null ? "" : cbbLoaiMay1.getSelectedItem() + "";
        String phienBan = cbbPhienBan1.getSelectedItem() == null ? "" : cbbPhienBan1.getSelectedItem() + "";
        String ram = cbbRAM1.getSelectedItem() == null ? "" : cbbRAM1.getSelectedItem() + "";
        String dungLuong = cbbDungLuong1.getSelectedItem() == null ? "" : cbbDungLuong1.getSelectedItem() + "";
        list = sptdao.select(txtTim.getText(), hang, dong, loai, phienBan, ram, dungLuong, page);
        if (list.size() == 21) {
            for(int i=0;i<20;i++){
                SanPhamTable x=list.get(i);
                model.addRow(new Object[]{x.getMa(), x.getTen(), x.getRam(), x.getDungLuong(), x.getMau(), x.isTinhTrang() ? "Mới" : "Cũ", Xmoney.moneyToString(x.getGia()), x.getSoLuong()});
            }
        } else {
            for (SanPhamTable x : list) {
                model.addRow(new Object[]{x.getMa(), x.getTen(), x.getRam(), x.getDungLuong(), x.getMau(), x.isTinhTrang() ? "Mới" : "Cũ", Xmoney.moneyToString(x.getGia()), x.getSoLuong()});
            }
        }
        updatePage(list);
    }

    void nextPage() {
        page++;
        fillTable();
    }

    void prevPage() {
        page--;
        fillTable();
    }

    void updatePage(List<SanPhamTable> list) {
        boolean prev = page != 0;
        boolean next = list.size() == 21;
        btnNext.setEnabled(next);
        btnPrevious.setEnabled(prev);
    }

    void updatePageRac(List<SanPham> list) {
        boolean prev = pageRac != 0;
        boolean next = list.size() == 11;
        btnNext3.setEnabled(next);
        btnPrevious3.setEnabled(prev);
    }

    void nextPageRac() {
        pageRac++;
        fillTableThungRac();
    }

    void prevPageRac() {
        pageRac--;
        fillTableThungRac();
    }

    void fillTableThungRac() {
        modelRac = (DefaultTableModel) tblThungRac.getModel();
        modelRac.setRowCount(0);
        lstSP = spdao.selectDisable(pageRac);
        for (int i = 0; i < lstSP.size(); i++) {
            SanPham sp = lstSP.get(i);
            Mau mau = maudao.selectById(sp.getColorId());
            LoaiMay lm = lmdao.selectById(sp.getModelId());
            Object[] rowData = new Object[]{
                sp.getIdProduct(),
                lm.getName(),
                sp.getRam(),
                sp.getSize(),
                lm.getName(),
                mau.getName(),
                sp.isIsnew() ? "Mới" : "Cũ",
                Xmoney.moneyToString(sp.getPrice()),
                sp.getCount()
            };
            modelRac.addRow(rowData);
        }
        updatePageRac(lstSP);
    }

    private void chonAnh() {
        JFileChooser jfc = new JFileChooser("src/com/DungNgoc/image");
        if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = jfc.getSelectedFile();
            Ximage.save(file);
            ImageIcon icon = Ximage.read(file.getName());
            lblAnh.setIcon(icon);
            lblAnh.setToolTipText(file.getName());
        }
    }

    void first() {
        this.index = 0;
        this.edit();
    }

    void prev() {
        if (this.index > 0) {
            this.index--;
            this.edit();
        }
    }

    void next() {
        if (this.index < tblSanPham.getRowCount() - 1) {
            this.index++;
            this.edit();
        }
    }

    void last() {
        this.index = tblSanPham.getRowCount() - 1;
        this.edit();
    }

    private void edit() {
        String maSP = (String) tblSanPham.getValueAt(this.index, 0);
        SanPham sp = spdao.selectById(maSP);
        this.setForm(sp);
        tabs.setSelectedIndex(1);
        this.updateStatus();

    }

    private void setForm(SanPham sp) {
        LoaiMay lm = lmdao.selectById(sp.getModelId());
        DongMay dm = dmdao.selectById(lm.getTag());
        HangMay hm = hmdao.selectById(dm.getTypeId());
        Mau mau = maudao.selectById(sp.getColorId());
        PhienBan pb = pbdao.selectById(sp.getVersionId());
        txtMaSP.setText(sp.getIdProduct());
        txtTenSP.setText(lm.getName());
        txtGiaSP.setText(String.valueOf(Xmoney.moneyToString(sp.getPrice())));
        txtSoLuong.setText(String.valueOf(sp.getCount()));
        cbbHangMay.setSelectedItem(hm.getName());
        cbbDongMay.setSelectedItem(dm.getName());
        cbbLoaiMay.setSelectedItem(lm.getName());
        cbbMauMay.setSelectedItem(mau.getName());
        cbbDungLuong.setSelectedItem(sp.getSize());
        cbbRAM.setSelectedItem(sp.getRam());
        cbbPhienBan.setSelectedItem(pb.getName());
        if (sp.getImage() != null) {
            lblAnh.setToolTipText(sp.getImage());
            lblAnh.setIcon(Ximage.read(sp.getImage()));
        }
        if (sp.isIsnew()) {
            radioMayMoi.setSelected(true);
        } else {
            radioMayMoi.setSelected(true);
        }

    }

    private void updateStatus() {
        boolean edit = (this.index >= 0);
        boolean first = (this.index == 0);
        boolean last = (this.index == tblSanPham.getRowCount() - 1);
        //Trạng thái form
        txtMaSP.setEditable(!edit);
        txtTenSP.setEditable(false);
        btnThem.setEnabled(!edit);
        btnSua.setEnabled(edit);
        btnXoa.setEnabled(edit);
        //Trạng thái điều hướng
        btnDau.setEnabled(edit && !first);
        btnLui.setEnabled(edit && !first);
        btnTien.setEnabled(edit && !last);
        btnCuoi.setEnabled(edit && !last);
    }

    private SanPham getForm() {
        LoaiMay lm = listLM.get(cbbLoaiMay.getSelectedIndex());
        Mau mau = listMau.get(cbbMauMay.getSelectedIndex());
        PhienBan pb = listPB.get(cbbPhienBan.getSelectedIndex());
        SanPham sp = new SanPham();
        if (txtMaSP.getText().trim().length() == 0 || txtGiaSP.getText().trim().length() == 0 || txtSoLuong.getText().trim().length() == 0) {
            MsgBox.alert(this, "Không được để trống thông tin sản phẩm");
            return null;
        }
        if (txtMaSP.getText().trim().matches("[^a-zA-Z0-9 ]+")) {
            MsgBox.alert(this, "Mã sản phẩm không chứa kí tự đặc biệt");
            return null;
        }
        if (!txtGiaSP.getText().trim().matches("[0-9 ]+")) {
            MsgBox.alert(this, "Giá phải là số");
            return null;
        }
        if (!txtGiaSP.getText().trim().matches("^[1-9][0-9]+$|[1-9]")) {
            MsgBox.alert(this, "Giá không bắt đầu từ 0");
            return null;
        }
        if (Double.parseDouble(txtGiaSP.getText().trim()) <= 0) {
            MsgBox.alert(this, "Giá phải lớn hơn 0");
            return null;
        }
        if (!txtSoLuong.getText().trim().matches("[0-9 ]+")) {
            MsgBox.alert(this, "Số lượng phải là số ");
            return null;
        }
        if (!txtSoLuong.getText().trim().matches("^[1-9][0-9]+$|[1-9]")) {
            MsgBox.alert(this, "Số lượng không bắt đầu từ 0");
            return null;
        }
        if (Integer.parseInt(txtSoLuong.getText().trim()) <= 0) {
            MsgBox.alert(this, "Số lượng phải lớn hơn 0");
            return null;
        }
        if (lblAnh.getToolTipText().isEmpty()) {
            MsgBox.alert(this, "Không để trống ảnh");
        }
        sp.setIdProduct(txtMaSP.getText());
        sp.setImage(lblAnh.getToolTipText());
        sp.setModelId(lm.getModelId());
        sp.setSize(String.valueOf(cbbDungLuong.getSelectedItem()));
        sp.setRam(String.valueOf(cbbRAM.getSelectedItem()));
        sp.setColorId(mau.getColorId());
        sp.setIsnew(radioMayMoi.isSelected());
        sp.setVersionId(pb.getVersionId());
        sp.setCount(Integer.parseInt(txtSoLuong.getText()));
        sp.setPrice(Double.parseDouble(txtGiaSP.getText()));
        sp.setDateAdd(Xdate.now());
        return sp;
    }

    private void insert() {
        SanPham sp = getForm();
        if (sp == null) {
            return;
        }
        int check = checkKey();
        if (check == 1) {
            MsgBox.alert(this, "Mã sản phẩm tồn tại");
            return;
        }
        try {
            spdao.insert(sp);
            this.fillTable();
            MsgBox.alert(this, "Thêm thành công");
        } catch (Exception e) {
            Exceptions.writeException(e, "Lỗi");
            MsgBox.alert(this, "Thêm thất bại");
            e.printStackTrace();
        }
        clearForm();

    }

// Loi anh, tien
    private void update() {
        SanPham sp = getForm();
        try {
            spdao.update(sp);
            this.fillTable();
            MsgBox.alert(this, "Sửa thành công");
            clearForm();
        } catch (Exception e) {
            MsgBox.alert(this, "Sửa thất bại");
            Exceptions.writeException(e, "Lỗi");
        }

    }

    private void delete() {
        if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền xóa sản phẩm");
        } else {
            String maSP = txtMaSP.getText();
            if (maSP == null) {
                MsgBox.alert(this, "Bạn chưa chọn sản phẩm để xóa");
            }
            if (MsgBox.confirm(this, "Bạn muốn xóa sản phẩm này?")) {
                try {
                    spdao.disable(maSP);
                    this.fillTableThungRac();
                    MsgBox.alert(this, "Xóa thành công");
                } catch (Exception e) {
                    Exceptions.writeException(e, "Lỗi");
                }
            }
            clearForm();
        }
    }

    private void clearForm() {
        SanPham sp = new SanPham();
        txtMaSP.setText("");
        txtTenSP.setText("");
        txtGiaSP.setText("");
        txtSoLuong.setText("");
        lblAnh.setIcon(null);
        this.index = -1;
        this.updateStatus();
    }

    private void restore() {
        if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền xóa sản phẩm");
        } else {
            index = tblThungRac.getSelectedRow();
            if (index >= 0) {
                String maSP = tblThungRac.getValueAt(index, 0).toString();
                if (maSP == null) {
                    MsgBox.alert(this, "Bạn chưa chọn sản phẩm để khôi phục");
                }
                if (MsgBox.confirm(this, "Bạn muốn khôi phục sản phẩm này?")) {
                    try {
                        spdao.reStore(maSP);
                        this.fillTableThungRac();
                        this.fillTable();
                        MsgBox.alert(this, "Khôi phục thành công");
                    } catch (Exception e) {
                        MsgBox.alert(this, "Khôi phục thất bại");
                        Exceptions.writeException(e, "Lỗi");
                    }
                }
            } else {
                MsgBox.alert(this, "Bạn chưa chọn sản phẩm cần khôi phục");
            }
        }
    }

    private void fillMau() {
        try {
            listMau.clear();
        } catch (Exception e) {
        }
        cbbMauMay.removeAllItems();
        listMau = maudao.selectAll();
        for (Mau x : listMau) {
            cbbMauMay.addItem(x.getName());
        }
    }

    int checkKey() {
        int check = 0;
        String maSP = txtMaSP.getText();
        for (SanPhamTable x : list) {
            if (x.getMa().trim().equalsIgnoreCase(maSP)) {
                check = 1;
            }
        }
        return check;
    }

}
