/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.DungNgoc.UI;

import com.DungNgoc.DAO.HoaDonChiTietDAO;
import com.DungNgoc.DAO.HoaDonDAO;
import com.DungNgoc.DAO.KhachHangDAO;
import com.DungNgoc.entitys.HoaDon;
import com.DungNgoc.entitys.HoaDonChiTiet;
import com.DungNgoc.entitys.KhachHang;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LINH
 */
public class JThongKeKhachHang extends javax.swing.JInternalFrame {

    /**
     * Creates new form JThongKeKhachHang
     */
    KhachHangDAO khdao = new KhachHangDAO();
    HoaDonDAO hddao = new HoaDonDAO();
    HoaDonChiTietDAO hdctdao = new HoaDonChiTietDAO();
    DefaultTableModel dtm;
    DecimalFormat df = new DecimalFormat("#.000");
    int sl;

    public JThongKeKhachHang() {
        initComponents();
        this.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTKKhachHang = new javax.swing.JTable();
        btnShow = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Thống Kê Khách Hàng");

        tblTKKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Khách Hàng", "Tên Khách Hành", "Số Lượng Mua", "Tổng Tiền"
            }
        ));
        jScrollPane1.setViewportView(tblTKKhachHang);

        btnShow.setText("Show Biểu Đồ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnShow))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnShow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblTKKhachHang;
    // End of variables declaration//GEN-END:variables
private void init() {
        dtm = (DefaultTableModel) tblTKKhachHang.getModel();
        sl = 0;
        this.filltable();
    }

    private int tongSoLuong(String IdGuest) {
        int soluong = 0;
        List<HoaDon> lsthd = hddao.selectByIdGuest(IdGuest);
        for (int j = 0; j < lsthd.size(); j++) {
            HoaDon hd = (HoaDon) lsthd.get(j);
            List<HoaDonChiTiet> lsthdct = hdctdao.selectById(hd.getIdBill(), null);
            for (int i = 0; i < lsthdct.size(); i++) {
                soluong += lsthdct.get(i).getCount();
            }
        }
        return soluong;
    }

    private void filltable() {
        List<KhachHang> lstkh = khdao.selectAll();
        for (int i = 0; i < lstkh.size(); i++) {
            KhachHang kh = (KhachHang) lstkh.get(i);
            sl = 0;
            sl = this.tongSoLuong(kh.getIdGuest());
            Object[] rd = new Object[]{
                kh.getIdGuest(),
                kh.getName(),
                sl,
                df.format(kh.getTotalMoney())
            };
            dtm.addRow(rd);
            
        }
    }
}
